pipeline:
  identifier: Build_rohan_bhaumik_careers_page_webapp_1772725500864
  name: Build careers-page-webapp
  orgIdentifier: Tests_all_the_way
  projectIdentifier: Testing_TI
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: org.connector_Github_d5a9
        repoName: rohan-bhaumik/careers-page-webapp
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  type: Run
                  spec:
                    image: node:20
                    shell: Bash
                    command: npm install
              - step:
                  identifier: lint
                  name: lint
                  type: Run
                  spec:
                    image: node:20
                    shell: Bash
                    command: npm run lint
              - step:
                  identifier: build
                  name: build
                  type: Run
                  spec:
                    image: node:20
                    shell: Bash
                    command: npm run build
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
  description: This pipeline was generated by Harness AI on 2026-03-05 17:48:15 UTC by DevOps Agent.
  tags:
    ai_generated: "true"
